import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CalendarDays, Check, Heart, Megaphone, UsersRound } from 'lucide-react';
import { useState } from 'react';
import { apiRequest } from '../api/client';
import { Button } from '../components/button';
import { EmptyState, InlineError } from '../components/query-state';

type Tab = 'events' | 'clubs' | 'announcements';
interface Event { _id: string; title: string; description: string; date: string; startTime: string; endTime: string; location: string; category: string; registrationLimit: number; registrationCount: number; isRegistered?: boolean; }
interface Club { _id: string; name: string; description: string; category: string; followerCount: number; isFollowing?: boolean; }
interface Announcement { _id: string; title: string; content: string; priority: string; publishDate: string; authorId?: { firstName: string; lastName: string; role: string }; }
interface List<T> { items: T[]; }
const tabs: Array<{ id: Tab; label: string; icon: typeof CalendarDays }> = [{ id: 'events', label: 'Events', icon: CalendarDays }, { id: 'clubs', label: 'Communities', icon: UsersRound }, { id: 'announcements', label: 'Official notices', icon: Megaphone }];

export function DiscoverPage() { const [tab, setTab] = useState<Tab>('events'); const client = useQueryClient(); const events = useQuery({ queryKey: ['events'], enabled: tab === 'events', queryFn: async () => (await apiRequest<List<Event>>('/api/events?limit=30', { authenticated: true })).data! }); const clubs = useQuery({ queryKey: ['clubs'], enabled: tab === 'clubs', queryFn: async () => (await apiRequest<List<Club>>('/api/clubs?limit=30', { authenticated: true })).data! }); const announcements = useQuery({ queryKey: ['announcements'], enabled: tab === 'announcements', queryFn: async () => (await apiRequest<List<Announcement>>('/api/announcements?limit=30', { authenticated: true })).data! }); const register = useMutation({ mutationFn: (id: string) => apiRequest(`/api/events/${id}/register`, { method: 'POST', authenticated: true }), onSuccess: () => client.invalidateQueries({ queryKey: ['events'] }) }); const follow = useMutation({ mutationFn: (id: string) => apiRequest(`/api/clubs/${id}/follow`, { method: 'POST', authenticated: true }), onSuccess: () => client.invalidateQueries({ queryKey: ['clubs'] }) }); const active = tab === 'events' ? events : tab === 'clubs' ? clubs : announcements; return <div><p className="text-xs font-bold uppercase tracking-[.14em] text-brand-600">Campus life</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Discover your community.</h1><p className="mt-2 text-sm text-slate-500">Events, communities, and verified updates—all in one place.</p><div className="mt-6 flex flex-wrap gap-2 border-b border-slate-200 pb-4 dark:border-slate-800">{tabs.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setTab(id)} className={`inline-flex h-10 items-center gap-2 rounded-lg px-3 text-sm font-semibold transition ${tab === id ? 'bg-brand-600 text-white' : 'text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-900'}`}><Icon size={16} />{label}</button>)}</div><section className="mt-6">{active.isLoading ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[1,2,3].map((i) => <div key={i} className="h-60 animate-pulse rounded-xl bg-slate-200 dark:bg-slate-800" />)}</div> : active.isError ? <InlineError message={(active.error as Error).message} /> : tab === 'events' ? <EventGrid events={events.data?.items ?? []} onRegister={(id) => register.mutate(id)} busy={register.isPending} /> : tab === 'clubs' ? <ClubGrid clubs={clubs.data?.items ?? []} onFollow={(id) => follow.mutate(id)} busy={follow.isPending} /> : <AnnouncementFeed items={announcements.data?.items ?? []} />}</section></div>; }

function EventGrid({ events, onRegister, busy }: { events: Event[]; onRegister: (id: string) => void; busy: boolean }) { if (!events.length) return <EmptyState title="No upcoming events" body="New workshops, cultural events, and club activities will appear here." icon={<CalendarDays size={20} />} />; return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{events.map((event) => <article key={event._id} className="flex min-h-60 flex-col rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between"><span className="rounded-full bg-brand-50 px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-brand-700 dark:bg-brand-500/10 dark:text-blue-200">{event.category}</span><span className="text-xs font-semibold text-slate-500">{new Date(event.date).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}</span></div><h2 className="mt-4 text-lg font-semibold">{event.title}</h2><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-500">{event.description}</p><p className="mt-4 text-xs text-slate-500">{event.startTime}–{event.endTime} · {event.location}</p><div className="mt-auto flex items-center justify-between pt-5"><span className="text-xs text-slate-500">{event.registrationLimit - event.registrationCount} spaces left</span>{event.isRegistered ? <span className="inline-flex items-center gap-1 text-xs font-semibold text-emerald-600"><Check size={15} /> Registered</span> : <Button className="h-9" onClick={() => onRegister(event._id)} disabled={busy}>Register</Button>}</div></article>)}</div>; }
function ClubGrid({ clubs, onFollow, busy }: { clubs: Club[]; onFollow: (id: string) => void; busy: boolean }) { if (!clubs.length) return <EmptyState title="No communities yet" body="Approved student communities will appear here." icon={<UsersRound size={20} />} />; return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{clubs.map((club) => <article key={club._id} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><span className="grid size-10 place-items-center rounded-xl bg-violet-50 text-violet-600 dark:bg-violet-500/10"><UsersRound size={19} /></span><p className="mt-5 text-xs font-bold uppercase tracking-wide text-violet-600">{club.category}</p><h2 className="mt-1 text-lg font-semibold">{club.name}</h2><p className="mt-2 line-clamp-3 text-sm leading-6 text-slate-500">{club.description}</p><div className="mt-5 flex items-center justify-between"><span className="text-xs text-slate-500">{club.followerCount} followers</span>{club.isFollowing ? <span className="text-xs font-semibold text-emerald-600">Following</span> : <Button className="h-9" variant="secondary" disabled={busy} onClick={() => onFollow(club._id)}><Heart size={15} /> Follow</Button>}</div></article>)}</div>; }
function AnnouncementFeed({ items }: { items: Announcement[] }) { if (!items.length) return <EmptyState title="No official notices" body="Verified announcements from authorized campus teams will appear here." icon={<Megaphone size={20} />} />; return <div className="mx-auto max-w-3xl space-y-3">{items.map((item) => <article key={item._id} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-brand-50 px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-brand-700 dark:bg-brand-500/10">Official · {item.priority}</span><span className="text-xs text-slate-500">{new Date(item.publishDate).toLocaleDateString()}</span></div><h2 className="mt-3 text-lg font-semibold">{item.title}</h2><p className="mt-2 whitespace-pre-line text-sm leading-6 text-slate-600 dark:text-slate-300">{item.content}</p><p className="mt-4 text-xs font-medium text-slate-500">Verified campus announcement{item.authorId ? ` · ${item.authorId.firstName} ${item.authorId.lastName}` : ''}</p></article>)}</div>; }
